//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameCompaniesDotComExtractor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"operationName\":\"getIndustryCompaniesBySlug\",\"variables\":{\"industrySlug\":\"%indus" +
            "trySlug%\",\"sortByName\":1,\"tagNames\":[],\"limit\":10000,\"offset\":0},\"query\":\"query " +
            "getIndustryCompaniesBySlug($citySlug: String, $countrySlug: String, $industrySlu" +
            "g: String, $limit: Int, $offset: Int, $regionSlug: String, $sortByName: Int, $ta" +
            "gNames: [String]) {\\n  result: getIndustryCompaniesBySlug(app: \\\"gcinsider\\\", ci" +
            "tySlug: $citySlug, countrySlug: $countrySlug, industrySlug: $industrySlug, limit" +
            ": $limit, offset: $offset, regionSlug: $regionSlug, sortByName: $sortByName, tag" +
            "Names: $tagNames) {\\n    total\\n    industrySlug\\n    companies {\\n      _id\\n  " +
            "    name\\n      slug\\n      short\\n      description\\n      picRelUrl\\n      cov" +
            "erRelUrl\\n      website\\n      jobWebsite\\n    imgs {\\n      _id\\n      path\\n  " +
            "    __typename\\n    }\\n    tags {\\n      _id\\n      name\\n      __typename\\n    " +
            "}\\n    nrOfEmployees\\n    established\\n    locations {\\n      _id\\n      latitud" +
            "e\\n      longitude\\n      formattedAddress\\n      __typename\\n    }\\n    headqua" +
            "rters {\\n      _id\\n      fullAddress\\n      countryDoc {\\n        _id\\n        " +
            "name\\n        slug\\n        adjective\\n        __typename\\n      }\\n      region" +
            "Doc {\\n        _id\\n        name\\n        slug\\n        __typename\\n      }\\n   " +
            "   cityDoc {\\n        _id\\n        name\\n        slug\\n        __typename\\n     " +
            " }\\n      __typename\\n    }\\n      firstTag {\\n        _id\\n        name\\n      " +
            "  __typename\\n      }\\n      picRelUrl\\n      firstLocation(industrySlug: $indus" +
            "trySlug, countrySlug: $countrySlug, regionSlug: $regionSlug, citySlug: $citySlug" +
            ") {\\n        _id\\n        countryDoc {\\n          _id\\n          name\\n         " +
            " slug\\n          adjective\\n          __typename\\n        }\\n        regionDoc {" +
            "\\n          _id\\n          name\\n          slug\\n          __typename\\n        }" +
            "\\n        cityDoc {\\n          _id\\n          name\\n          slug\\n          __" +
            "typename\\n        }\\n        __typename\\n      }\\n      __typename\\n    }\\n    _" +
            "_typename\\n  }\\n}\\n\"}")]
        public string Data1 {
            get {
                return ((string)(this["Data1"]));
            }
            set {
                this["Data1"] = value;
            }
        }
    }
}
